name: Build and Push Docker Image

on:
  push:
    tags:
      - "v*.*.*"
      - "v*.*.*-rc*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Extract the tag name from the git ref, excluding the leading "v"
      -
        uses: actions/github-script@v6
        id: extract-tag
        with:
          script: |
            const tag = context.ref.replace(/^refs\/tags\//, '')
            core.setOutput('tag', tag)
            core.setOutput('result-encoding', 'string')
            console.log(`Using tag: ${tag}`)
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sqrl-server:${{ steps.extract-tag.outputs.tag }}
